[[redirects]]
  from = "/proxy/*"
  to = "https://www.look-outside.ml/:splat"
  status = 200
  force = true
  
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.openweathermap.org/:splat"
  status = 200
  force = true