[[redirects]]
  from = "/proxy/*"
  to = "https://www.look-outside.ml/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/*"
  to = "https://api.openweathermap.org/data/2.5/group:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
